// Single source of truth for cross-module types.
// The `Env` interface itself is auto-generated by `wrangler types` into
// worker-configuration.d.ts (bindings + vars). We augment it here with
// the secrets we set via `wrangler secret put`.

export {};

declare global {
	interface Env {
		BOT_TOKEN: string;
		WEBHOOK_SECRET: string;
	}
}

export type UserRole = 'user' | 'admin' | 'superadmin';

export interface DbUser {
	id: number;
	telegram_id: string;
	full_name: string;
	user_role: UserRole;
	superior_telegram_id: string | null;
	ord_date: string | null;
	created_at: string;
}

export interface TgWebAppUser {
	id: number;
	first_name?: string;
	last_name?: string;
	username?: string;
	language_code?: string;
}

export type ParadeStatus =
	| 'Present'
	| 'Off'
	| 'Leave'
	| 'Overseas Leave'
	| 'MC'
	| 'Attached-Out'
	| 'Others';

export const PARADE_STATUSES: readonly ParadeStatus[] = [
	'Present',
	'Off',
	'Leave',
	'Overseas Leave',
	'MC',
	'Attached-Out',
	'Others',
];
